# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c9a05b0f8cfec1f92e6975158007bcad6378c5bd496cdfd138ad37644ca4d3fe87fa9fd1537791615baed5a5b7a99dafbea6cba389a2aea38232848474b0ca8

test:
  secret_key_base: 60db536cc0273a2bc0546790ca14cd662e4f618dcbd11e17d9bbaf1ae4a7ff9358ff10771230638a7421f9d71c2a2cca05cfb02f3b902e7f961fb251dbc92559

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
